#!/usr/bin/env node
// Builds dist/ and generated/ from content/. With --check, fails when the
// committed outputs are not what content/ builds to.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { at, loadContent, entriesOf, FIELD_ORDER } from './lib.mjs';

const content = loadContent();
const { meta } = content;
const entries = entriesOf(content)
  .map(({ entry }) => entry)
  .map((entry) => Object.fromEntries(
    Object.entries(entry).sort(([a], [b]) => FIELD_ORDER.indexOf(a) - FIELD_ORDER.indexOf(b)),
  ))
  .sort((a, b) => a.id.localeCompare(b.id));

const full = {
  ojg_version: meta.ojg_version,
  document: meta.document,
  source_policy: meta.source_policy,
  references: content.references.reference_sources,
  retired: meta.retired ?? [],
  entries,
};

const levels = meta.level_files.map((f) => f.level);
const statuses = meta.review_statuses.map((s) => s.id);
const count = (level, status) =>
  entries.filter((e) => e.levels.commonly === level && (!status || e.review.status === status))
    .length;
const total = (status) => entries.filter((e) => e.review.status === status).length;
const rows = levels.map((level) => {
  const name = level === 'none' ? 'Beyond JLPT' : level;
  return `| ${name} | ${count(level)} | ${statuses.map((s) => count(level, s)).join(' | ')} |`;
});

const byPattern = new Map();
for (const e of entries) byPattern.set(e.pattern, [...(byPattern.get(e.pattern) ?? []), e]);
const shared = [...byPattern].filter(([, list]) => list.length > 1);
const sharedLines = shared.length
  ? shared
      .map(([p, list]) => `- ${p}: ${list.map((e) => `${e.id} (${e.levels.commonly})`).join(', ')}`)
      .join('\n')
  : 'None.';

const coverage = [
  '# Coverage',
  '',
  'Generated by `scripts/build.mjs`. Do not edit.',
  '',
  `| Level | Entries | ${statuses.join(' | ')} |`,
  `|---|---|${statuses.map(() => '---').join('|')}|`,
  ...rows,
  `| **All** | **${entries.length}** | ${statuses.map((s) => `**${total(s)}**`).join(' | ')} |`,
  '',
  '## The same pattern under more than one id',
  '',
  'Usually one pattern with two uses, or a source listing it at two levels.',
  'Each wants a person to decide: two points, or one to merge.',
  '',
  sharedLines,
  '',
].join('\n');

const outputs = {
  'dist/ojg.full.json': JSON.stringify(full, null, 2) + '\n',
  'dist/ojg.jsonl': entries.map((e) => JSON.stringify(e)).join('\n') + '\n',
  'generated/coverage.md': coverage,
};

if (process.argv.includes('--check')) {
  const stale = Object.entries(outputs)
    .filter(([path, text]) => !existsSync(at(path)) || readFileSync(at(path), 'utf8') !== text)
    .map(([path]) => path);
  if (stale.length) {
    console.error(`build: out of date, run npm run build: ${stale.join(', ')}`);
    process.exit(1);
  }
  console.log('build: outputs match content');
} else {
  for (const [path, text] of Object.entries(outputs)) {
    mkdirSync(dirname(at(path)), { recursive: true });
    writeFileSync(at(path), text);
  }
  console.log(`build: ${entries.length} entries written to dist/ and generated/`);
}
